name: dev stats
on:
  schedule:
    - cron: "0 8,18 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 0ddf29ce7548840ac6ccd205aabfc3ee
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
